/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {
    public static void main(String[] args) throws IOException {

        URL ex = new URL("https://codefellows.github.io/code-401-java-guide/curriculum/class-08/recentquotes.json");
        BufferedReader reader = new BufferedReader(
                new InputStreamReader(ex.openStream()));
        Gson gson1 = new Gson();
        Quote[] Quot = gson1.fromJson(reader, Quote[].class);
        int ind;
        ind = (int) (Math.random() * Quot.length);
        String Author = Quot[ind].getAuthor();
        String Text = Quot[ind].getText();
        System.out.println("Author : " + Author + "\nQuote : \" " + Text + " \"");

        System.out.println("//////////////////////////////////////////");

        try {

            URL Url = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
            HttpURLConnection HttpURLConnection = (HttpURLConnection) Url.openConnection();
            HttpURLConnection.setRequestMethod("GET");
            InputStreamReader InputStreamReader = new InputStreamReader(HttpURLConnection.getInputStream());
            BufferedReader BufferedReader = new BufferedReader(InputStreamReader);
            String Data = BufferedReader.readLine();
            System.out.println(Data);
            Gson gson = new Gson();
            Favqoutes Quote = gson.fromJson(Data, Favqoutes.class);
            System.out.println(Quote);
            File dittoFile = new File("./ditto.json");
            try (FileWriter dittoFileWriter = new FileWriter(dittoFile)) {
                gson.toJson(Quote, dittoFileWriter);

            }
        } catch (Exception e) {
            Gson gson2 = new Gson();
            Reader reader1 = Files.newBufferedReader(Paths.get("ditto.json"));
            Favqoutes Quot1 = gson2.fromJson(reader1, Favqoutes.class);
            System.out.println("Author" + Quot1.getAuthor());
            System.out.println("Quot" + Quot1.getBody());

        }
    }
}

//        1 pt show random quotes in terminal from API
//        1 pt show random quotes in terminal from file when internet connectivity is down
//        1 pt for appending API quote to JSON file
//        2 pts for tests passing in terminal and IDE
//        1 pt for README with clear instructions on how to run application


